#!/usr/bin/env bash
# is RSA-Factoring-Challenge

check_factor()
{
	if [ $# -ne 3 ];
        then
                args=("$@")
                count=0
                num=1
                for a in ${args[*]};
                do
                        if [ $count -gt 1 ];
                        then
                                num=$(echo $a*$num | bc)
                        fi
                        count=$((count + 1))
                done
        else
                num=$3
        fi

        num1=$2
        num=$(echo "$1" | tr ':' '=')

        result=$(echo "if($num > $num1) 1 else 0" | bc)
	        if ((result == 1)); then
		        numcp=$num1
		        num1=$num
		        num=$numcp
                fi

        echo "$num$num1*$num"
}

if [ $# -ne 1 ]
then
        echo 'Usage: factors <file>'
        exit 1
else

        while read i
        do

                result=$(factor "$i")
                check_factor $result

        done < "$1"
fi
